[package]
name = "proyecto3-planetas"
version = "0.1.0"
edition = "2024"

[dependencies]
minifb = "0.27.0"
nalgebra-glm = "0.19.0"
fastnoise-lite = "1.1.1"
tobj = "4.0.2"
image = { version = "0.24", default-features = false, features = ["png"] }
